name: CLI Regression Test

on:
  workflow_dispatch:
    inputs:
      key:
        description: 'Secret'
        required: true

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: |
          "THIS IS THE STEP"
        env:
          KEY: ${{ inputs.key }}
  cli-regression-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -ileo pipefail {0}

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
        with: 
          persist-credentials: 'false'
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup virtual env
        uses: ./.github/actions/make_init
      - name: Build Package - Fast
        timeout-minutes: 120
        run: |
          sudo apt-get install rsync
          BUILD_AS_FAST_AS_POSSIBLE=1 make package
      - name: Run CLI regression tests
        run: export SKIP_VERSION_CHECK=true; make cli-regression-tests