name: Python Prod Deps Smoke Test

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - '**'
  workflow_call:

# Avoid duplicate workflows on same branch
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-prod-deps-smoke-test:
    runs-on: ubuntu-latest

    # permissions:
    #   actions: read

    defaults:
      run:
        shell: bash -ileo pipefail {0}

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
        with: 
          persist-credentials: false
          submodules: 'recursive'
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup virtual env
        uses: ./.github/actions/make_init
        with:
          use_cached_venv: 'false'
      - name: Run make develop
        run: make develop
      - name: Run CLI smoke tests
        run: make cli-smoke-tests
